### ISSUE TITLE
You can just hide the cursor with an escape code

### ISSUE THREAD

**Issue by bwasti** [SeungheonOh/pot#1]
https://github.com/SeungheonOh/PixelOnTerminal/blob/9ab64ca0affd8105dbb7162b99bf75b07fac70dd/main.go#L74

```
    fmt.Print("\033[?25l")
```
but be sure to show it again on shutdown
```
    fmt.Print("\033[?25h")
```

**Comment by frebib** [comment]
Implemented in #3
