### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by misuchiru03** [SeungheonOh/pot#4]
This is awesome! Would you mind tagging a release version?  Thank you!

**Comment by SeungheonOh** [comment]
Okay, Ill do that this afternoon!

**Comment by SeungheonOh** [comment]
Sorry, I was really busy doing school things,, release it now there, for Arch Linux,, well I might need to setup docker to build Debian/Ubuntu. :wink:

**Comment by SeungheonOh** [comment]
Forgot the close the issue oof
