### ISSUE TITLE
-r option for video subcommand results in frozen playback after gif ends

### ISSUE THREAD

**Issue by Phate6660** [SeungheonOh/pot#6]
I might be wrong, but I assume that the `-r` option for the `video` subcommand is for repeating/looping the video or gif right?

If so, I think it might be broken for gifs. No matter what gif I try, on any terminal, and on any shell, once the gif is over it just freezes. I have to close the terminal or ctrl-c out of it.

It does work perfectly fine for videos though, at least from what I can tell.

**Comment by SeungheonOh** [comment]
Oh thanks I'll fix that this afternoon!

**Comment by SeungheonOh** [comment]
Wired, I tried it, did worked fine;; I could not reproduce the issue

**Comment by Phate6660** [comment]
Odd. Perhaps it's a problem with my gifs or my terminal?

I've tried it on `xterm`, as well as various VTE-based terminals. I've also attempted to use it with a multitude of gifs.

Can you think of anything that could cause it to happen? It'll play the gif just fine normally, but when the gif finishes and it goes to loop the gif just freezes and I have to ctrl-c out of it.

**Comment by SeungheonOh** [comment]
Xterm is perfectly fine, in fact most other VT emulator should be okay, I've tried Urxvt, st, kitty, and few more 

Did you put -r option infront of file name?

**Comment by Phate6660** [comment]
Yep, I made sure to.

**Comment by SeungheonOh** [comment]
That is wired indeed. For now, the only I can think of is OpenCV itself

**Comment by SeungheonOh** [comment]
Just in case, can I get your system specs and OpenCV version?

**Comment by Phate6660** [comment]
Distro: Gentoo
XTerm Version: 351
Shell: BASH 4.4.23
OpenCV Version: 4.1.2-r2 | [I have most USE flags for it disabled](https://privatebin.net/?b2860f09a0221300#CKjxcJDeCEJbTsNWMMpqCs8jMSPtGKhmXaZouMFpUFJB).

I hope this is enough info. I didn't know how much to give.

**Comment by SeungheonOh** [comment]
Maybe it's OpenCV version, the newest release is 4.2.0, except that, I really can't find any reason why it wouldn't work

**Comment by Phate6660** [comment]
I can't go any higher, that's the highest version the Gentoo repos have.

Oh well. Looping isn't super important I guess. Thanks for helping.

**Comment by SeungheonOh** [comment]
You are using Gentoo, build it by yourself 🤣. 
Most recent release is available here: https://opencv.org/releases/

**Comment by Phate6660** [comment]
I'd rather not. I dislike installing things outside of the package manager.

Plus, PixelOnTerminal mostly works anyways, it's just looping that is broken for me. I'd rather not compile another version outside of the package manager just to hopefully fix one feature.

**Comment by SeungheonOh** [comment]
Fair enough! I'll let you know if I find anything that might fix the problem
