### ISSUE TITLE
how to use it as library

### ISSUE THREAD

**Issue by ghost** [SeungheonOh/pot#7]
Hi,

Hope you are all well !

How to use it as a library if I want to embed it in one of my golang projects ?

Thanks in advance for any insights or inputs on that topic.

Cheers,
X

**Comment by SeungheonOh** [comment]
You can take the renderer parts. You would still need Gocv since the renderers loads images from Opencv mat. If you let me know what you are trying, I can make some modifications to make it more portable.

Best,
Seungheon Oh

**Comment by ghost** [comment]
Hi,

I have created a modular scraping system and I define a logo for each plugin scraping a website.
For eg, I define an ascii logo, https://github.com/lucmichalski/peaks-tires/blob/master/plugins/oscaro.com/plugin.go#L83

Then, when I load my go plugin, I print it in the terminal.
https://github.com/lucmichalski/peaks-tires/blob/master/main.go#L392

In a nutshell, when I load a plugin, I print its ASCII logo but want to convert to brand logo, for fun, like PixelOnTerminal.

Cheers,
X

**Comment by SeungheonOh** [comment]
Nice project you've got there, 
I've updated the renderers so that they return string of the image. Once you load your images into opencv Mat( using gocv ), you'll be able to use the renderer package. Feel free to ask/suggest anything. 

Best,
Seungheon Oh

**Comment by ghost** [comment]
Can you provide code snippet ? or write an example for the project ?

**Comment by SeungheonOh** [comment]
It's getting late here, I think I could write you a snippet tomorrow.

However, here's brief way of doing it.
https://github.com/SeungheonOh/PixelOnTerminal/blob/master/commands/image.go at load function is how you load the image. Once you get the image, just call one of the renderers(ascii, ascii-256, unicode-256 ...) and it will output a string. Pretty simple.

Best,
Seungheon Oh

**Comment by ghost** [comment]
yeah, it would be awesome to have a snippet. :-)

**Comment by SeungheonOh** [comment]
Sorry, I didn't have access to the PC, but here's the snippet.

```go
package main

import (
  "image"
  "fmt"

  "github.com/SeungheonOh/PixelOnTerminal/renderer"
  cv "gocv.io/x/gocv"
)

func main() {
  img := cv.IMRead("/home/seungheonoh/test.png", 1)
  if img.Empty() {
    panic("Failed to load image")
  }

  ascii, err := renderer.HighRes(img, image.Point{30, 30})
  if err != nil {
    panic(err)
  }
  fmt.Println(ascii)
}
```
![Apr-11-2020-10:44](https://user-images.githubusercontent.com/24271442/79048285-ae477c80-7be1-11ea-9d09-df95969bea3b.jpg)

**Comment by ghost** [comment]
wonderful will test now... thanks again

**Comment by SeungheonOh** [comment]
Any updates? Can I close this issue?

**Comment by ghost** [comment]
thanks for your help :-)
